### ISSUE TITLE
_mysql_exceptions.OperationalError

### ISSUE THREAD

**Issue by icydevx** [taroved/pol#17]
Not sure where does it go wrong...no error running Initialise database script.
Please help, thank you very much.

MySQL version: 5.7.22-0ubuntu0.16.04.1

**After created the Feed, it shows:**

Something wrong. Reload the page or contact us by email

**When I click on the Feed link, it shows:**

web.Server Traceback (most recent call last):
_mysql_exceptions.OperationalError: (1054, "Unknown column 'f.name' in 'field list'")

**Error log in Backend:**

2018-06-26T00:19:57+0800 [twisted.web.server.Request#critical] 
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 572, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 2054, in lineReceived
	    self.allContentReceived()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 2145, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 890, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 197, in process
	    self.render(resrc)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 257, in render
	    body = resrc.render(self)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "/root/pol/pol/server.py", line 340, in render_GET
	    res = self.feed.getFeedData(feed_id)
	  File "/root/pol/pol/feed.py", line 160, in getFeedData
	    where f.id=%s""", (feed_id,))
	  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorvalue
	_mysql_exceptions.OperationalError: (1054, "Unknown column 'f.name' in 'field list'")

**Error log in Frontend:**

[25/Jun/2018 16:19:52] "POST /setup_get_selected_ids HTTP/1.0" 200 773
/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py:124: Warning: Field 'owner_id' doesn't have a default value
  return self.cursor.execute(query, args)

[25/Jun/2018 16:19:53] "POST /setup_create_feed HTTP/1.0" 200 13
[25/Jun/2018 16:19:54] "GET /en/preview/1 HTTP/1.0" 200 7168

**Comment by icydevx** [comment]
errr...OK I made it finally, the module python-sqlparse is missing so that the database is not imported properly, thanks.
