### ISSUE TITLE
Docker isntall borks :(

### ISSUE THREAD

**Issue by gerroon** [taroved/pol#44]
Debian testing x64

`docker-compose up -d --build`

```
 Downloading Scrapy-1.4.0-py2.py3-none-any.whl (248 kB)
Collecting django-pipeline==1.5.4
  Downloading django_pipeline-1.5.4-py2.py3-none-any.whl (29 kB)
Collecting mysqlclient==1.3.7
  Downloading mysqlclient-1.3.7.tar.gz (79 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-TnjTQr/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-TnjTQr/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-TnjTQr/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-TnjTQr/mysqlclient/
    Complete output (10 lines):
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-TnjTQr/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'politepol' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

**Comment by Ineluki** [comment]
I've have the same issue but this fork works: https://github.com/marlluslustosa/pol

**Comment by gerroon** [comment]
Thanks for the link,  i still get an error with that one.

```
---> Running in 1909ecf590e2
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting Django==1.8.6
  Downloading Django-1.8.6-py2.py3-none-any.whl (6.2 MB)
Collecting lxml==3.8.0
  Downloading lxml-3.8.0-cp27-cp27mu-manylinux1_x86_64.whl (6.8 MB)
Collecting Scrapy==1.4.0
  Downloading Scrapy-1.4.0-py2.py3-none-any.whl (248 kB)
Collecting django-pipeline==1.5.4
  Downloading django_pipeline-1.5.4-py2.py3-none-any.whl (29 kB)
Collecting mysqlclient==1.3.7
  Downloading mysqlclient-1.3.7.tar.gz (79 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-riBf8j/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-riBf8j/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-riBf8j/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-riBf8j/mysqlclient/
    Complete output (10 lines):
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-riBf8j/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'politepol' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1


```
